import Head from 'next/head'
import Style from '../styles/layouts.module.css'
import Menu from './menu'

export default function Layouts({children, title}){
    return (
        <div>
            <Head>
                <title>GitHub Merch {title ? `| ${title}` : ""}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <div className={Style.container}>{children}</div>
        </div>
    )
}