import Head from 'next/head'

export default function Layouts({children, title}){
    return (
        <div>
            <Head>
                <title>GitHub Merch {title ? '| ${title}' : ""}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}